package by.doitnow.ownexception;

public class UnsuitableNumber extends Exception {
}
