package by.doitnow.ownexception;

public class UsedTwoDifferentSystem extends Exception {
}
